### ISSUE TITLE
Model.update is not a function

### ISSUE THREAD

**Issue by TofaDev** [sequelize/sequelize-typescript#1341]
**Issue**

Versions
- sequelize: ^7.0.0-alpha.10
- sequelize-typescript: ^2.1.3
- typescript: 4.6.4

Issue type

- [x] bug report
- [ ] feature request

Actual behavior

When trying to call the update method on a declared model variable, it throws an error that it is not a function

**Code:** 

`let user = await UserModel.findOne({
            where: { vkId },
            raw: true
        })

        if(!user) throw new Error(`User with ${vkId} VkId not found`)

        await user.update({balance: amount})

        await user.save()`

**UserModel import:** 

import UserModel from "../database/models/User";`
`

**UserModel file:** 

`
import sequelize from "../index";
import {DataTypes} from "@sequelize/core";

const User = sequelize.define(
    'users',
    {
        uid: {
            type: DataTypes.INTEGER,
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            unique: true
        },
        vkId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            unique: true
        },
        balance: {
            type: DataTypes.INTEGER,
            defaultValue: 0,
            allowNull: false
        }
    }, {timestamps: true, freezeTableName: true}
)

export default User
`

**sequelize file** 

`
import {Sequelize} from "sequelize-typescript";
import configuration from "../resources/configuration";

const databaseInfo = configuration.database.options
const connectionCredentials = configuration.database.connectionInfo

const sequelize = new Sequelize(databaseInfo.database,
    databaseInfo.user, databaseInfo.password,
{
        host: connectionCredentials.host,
        port: connectionCredentials.port || 3306,
        dialect: 'mariadb'
    }
)

sequelize.sync()
    .then(() => {
        console.log(`all tables synced`)
    })

export default sequelize
`

**Comment by kiranpoojary** [comment]
i think u have model name and local variable name as 'users'
