### ISSUE TITLE
Glob v7.2.1 breaks model path resolving [win32] 

### ISSUE THREAD

**Issue by skoniks** [sequelize/sequelize-typescript#1478]
# Issue

Globe commit https://github.com/isaacs/node-glob/commit/73feafd17f1c04633349652605e12fbbaef9b3cf forces minimatch config options **allowWindowsEscape** to **true**, this breaks Sequelize option `models`, when it is set to path, like `models: [__dirname + '/**/*.model.ts']` on windows system.

## Versions

- sequelize: 6.25.2
- sequelize-typescript: 2.1.4
- typescript: 4.8.3

## Issue type

- [x] bug report
- [ ] feature request

## Actual behavior

When applicaton starts, models are not initializing. When trying to use model you receive an exception `"Model not initialized: Member \"count\" cannot be called. \"User\" needs to be added to a Sequelize instance."`

## Steps to reproduce

- Install **sequelize-typescript@2.1.4**
- Set sequelize option to path, like `models: [__dirname + '/**/*.model.ts']`
- Run application on windows system

## Solving the problem

Revert Pull request https://github.com/sequelize/sequelize-typescript/pull/1327 - Downgrade Glob to [v7.2.0](https://github.com/isaacs/node-glob/releases/tag/v7.2.0)

**Comment by WikiRik** [comment]
Do you think this can also be solved by https://github.com/sequelize/sequelize-typescript/pull/1449 ?

**Comment by skoniks** [comment]
> Do you think this can also be solved by #1449 ?

Yes, it works.

**Comment by lukashroch** [comment]
It will fix it but we should revert anyway. Glob V8 only supports node12+ and sequlize v6 is still keeping node10 support, is that right @WikiRik?

**Comment by skoniks** [comment]
> That is correct, so reverting seems to be the better solution. Good catch!

Are you planning to include revert in release v2.1.5?

**Comment by lukashroch** [comment]
Yeah, will try to push bug fix out today.

**Comment by WikiRik** [comment]
Fixed in v2.1.5. Thanks for notifying us of this issue!
