### ISSUE TITLE
How to use auto generated functions ?

### ISSUE THREAD

**Issue by cth166** [sequelize/sequelize-typescript#1594]
[How to use auto generated functions (such as add Bar) in many-to-many relationship?](https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading/#multiple-eager-loading)
```js
const Foo = sequelize.define('Foo', { name: DataTypes.TEXT });
const Bar = sequelize.define('Bar', { name: DataTypes.TEXT });
Foo.belongsToMany(Bar, { through: 'Foo_Bar' });
Bar.belongsToMany(Foo, { through: 'Foo_Bar' });

await sequelize.sync();
const foo = await Foo.create({ name: 'foo' });
const bar = await Bar.create({ name: 'bar' });
await foo.addBar(bar);
const fetchedFoo = await Foo.findOne({ include: Bar });
```

I want to insert one in junction table in my demo.

I try to use $add but error
`TypeError: this[("add" + (0 , string_1.capitalize)(...))] is not a function
    at c.$add (C:\Users\cth16\Desktop\mysql2\node_modules\sequelize-typescript\dist\model\model\model.js:26:67)
    at C:\Users\cth16\Desktop\mysql2\dist\index.js:1:2970
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
![image-20230225043757818](https://user-images.githubusercontent.com/93234693/221287221-6ecf00cc-a1a4-492d-86b6-ec0ba5dda6d5.png)

**Comment by Dung24-6** [comment]
You can try  author.addBook(book) or await author.addBook(book, { through: { status: 'unread' }})
