### ISSUE TITLE
Question: Decorators in Typescript >= 5.0

### ISSUE THREAD

**Issue by fenghourun** [sequelize/sequelize-typescript#1655]
Is there plans to support [typesciprt 5.0 decorators](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators)? Should we plan to use `experimentalDecorators` for the foreseeable future?

**Comment by WikiRik** [comment]
@ephys I think you can answer what the plans are for sequelize v7 (either already in the beta or in a later minor release)

For context; the functionality from sequelize-typescript is a part of the 'regular' sequelize package starting with v7 (the next major release). Don't expect that support will be added in the current major release since progress on v7 is quite far

**Comment by ephys** [comment]
There are plans for supporting the new decorators format (sometimes after Sequelize 7 is stable). When we imported the decorators in `@sequelize/core`, we put all decorators that use the old format under `@sequelize/core/decorators-legacy` to be able to support the new decorators under `@sequelize/core/decorators`

**Comment by bkoltai** [comment]
I am using Typescript 5.1.6 and am trying to use `@sequelize/core/decorators-legacy` to declare my model classes.

This is an example of an import in one of my model declarations
```ts
import { Attribute, NotNull } from "@sequelize/core/decorators-legacy";
```

And I get the following TS error

```
Cannot find module '@sequelize/core/decorators-legacy' or its corresponding type declarations.
```

In my package.json I have
```json
{
  "dependencies": {
     ...
    "@sequelize/core": "alpha",
    ...
    "typescript": "5.1.6",
  }
}
```

And my tsconfig.json
```json
{
  "compilerOptions": {
    "sourceMap": true,
    "removeComments": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "target": "es2019",
    "types": ["node", "jest"],
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noEmit": false,
    "preserveWatchOutput": true,
    "assumeChangesOnlyAffectDirectDependencies": true,
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "src",
    "rootDir": "src",
    "outDir": "build",
    "isolatedModules": true,
    "experimentalDecorators": true
  },
  "exclude": ["node_modules", "scripts"],
  "include": ["./src"]
}
```

What am I missing to be able to import from `@sequelize/core/decorators-legacy`?
