### ISSUE TITLE
Disable UpdateAt decorator in specific query

### ISSUE THREAD

**Issue by oktapodia** [sequelize/sequelize-typescript#1693]
# Disable UpdateAt decorator in specific query

## Versions

- sequelize: 6.32.1
- sequelize-typescript: 2.1.5
- typescript: 5.2.2

## Issue type

- [x] bug report
- [ ] feature request

Hello, I am trying to disable the UpdatedAt decorator for a single migration query, I've found the `silent: true` options but it does not seems to be working fine.

Weird thing is that the query debug does not show that updatedAt update:
`Executing (719753b2-8f64-4eca-aa3b-58e79e7e5a98): UPDATE \"users\" SET "is_global"=$1 WHERE "status" != ''`

I did try with 
```
    await User.update({ isGlobal: true}, {
      where: {
        status: {
          [Op.ne]: '',
        },
      },
      transaction,
      silent: true
    })
  })
```
and
```
   user.isGlobal = true
   await user.save({ transaction, silent: true });
```

But I am having the same behavior, updatedAt gets updated to the current.

Thanks in advance

**Comment by blankstar85** [comment]
You probably have in the model definition in your version of sql an auto update. For Mysql: 
![image](https://github.com/sequelize/sequelize-typescript/assets/1760462/c822f433-5a64-4828-b99d-62563b75e71c)
