### ISSUE TITLE
Apologies if this is not the right forum to ask

### ISSUE THREAD

**Issue by MyCADDev** [sequelize/sequelize-typescript#1732]
Is this project dead? I dont see commits for past 10 months

**Comment by WikiRik** [comment]
No new functionality will be added to `sequelize-typescript`. In the next major release of `sequelize` (which is in alpha and will be released under [`@sequelize/core`](https://www.npmjs.com/package/@sequelize/core)) the functionality is built in and you do not need a separate package anymore.

**Comment by MyCADDev** [comment]
Thanks for the note.
