### ISSUE TITLE
Proper way to define types

### ISSUE THREAD

**Issue by urielvan** [sequelize/sequelize-typescript#340]
Hello
When I define classes, I need to add some columns to every class. e.g. status, remark
To be simple, it goes like this.
```ts
class ModelBase extends Model<ModelBase> {
  @Column
  status: number;

  @Column
  remark: string;
}

class Foo extends ModelBase {
  @Column
  foo: string;
}
```
When I using v0.6.1, it's ok with `var bar = new Foo ({ foo: 'foo' })`
But with v0.6.3, I cannot compile because `foo`  doesn't exists in type `FilteredModelAttributes<ModelBase>`

**Comment by RobinBuschmann** [comment]
Hey @urielvan, this is because you do not pass the generic type up to `Model`, so that the type information for the constructor typings (which are defined in `Model`)  cannot know of `Foo`'s properties. 
Try it like so instead:

```ts
class ModelBase<T extends Model<T>> extends Model<T> {
  @Column
  status: number;

  @Column
  remark: string;
}

class Foo extends ModelBase<Foo> {
  @Column
  foo: string;
}
```

**Comment by urielvan** [comment]
@RobinBuschmann Thanks so much for the help ! 😄
